DELIMITER $$
CREATE TRIGGER backup_DB
    BEFORE DELETE
    ON pedidos FOR EACH ROW
BEGIN
  INSERT INTO backup(ID,NUMBER,PRICE,COUNTRY,CP,DATEHOUR,DATE,HOUR,HOURAPROX,MONTH,WEEKDAY,ASIN)
    VALUES(OLD.ID,OLD.NUMBER,OLD.PRICE,OLD.COUNTRY,OLD.CP,OLD.DATEHOUR,OLD.DATE,OLD.HOUR,OLD.HOURAPROX,OLD.MONTH,OLD.WEEKDAY,OLD.ASIN);
    END$$    
DELIMITER;