DELIMITER $$
CREATE TRIGGER backup_DB
    BEFORE DELETE
    ON pedidos FOR EACH ROW
BEGIN
  INSERT INTO backup(ID,NUMBER,PRICE,COUNTRY,CP,DATEHOUR,DATE,HOUR,HOURAPROX,MONTH,WEEKDAY,ASIN)
    VALUES(OLD.ID,OLD.NUMBER,OLD.PRICE,OLD.COUNTRY,OLD.CP,OLD.DATEHOUR,OLD.DATE,OLD.HOUR,OLD.HOURAPROX,OLD.MONTH,OLD.WEEKDAY,OLD.ASIN);
    END$$    
DELIMITER;

--User & time

DROP TRIGGER IF EXISTS `backup_DB`;CREATE DEFINER=`root`@`localhost` TRIGGER `backup_DB` BEFORE DELETE ON `pedidos` FOR EACH ROW BEGIN INSERT INTO backup(ID,NUMBER,PRICE,COUNTRY,CP,DATEHOUR,DATE,HOUR,HOURAPROX,MONTH,WEEKDAY,ASIN) VALUES(OLD.ID,OLD.NUMBER,OLD.PRICE,OLD.COUNTRY,OLD.CP,OLD.DATEHOUR,OLD.DATE,OLD.HOUR,OLD.HOURAPROX,OLD.MONTH,OLD.WEEKDAY,OLD.ASIN,CURRENT_USER(), NOW()); END
